### ISSUE TITLE
Aa

### ISSUE THREAD

**Issue by tikiMC** [Tfarcenim/Quiver#1]
the quiver item needs to be capitalized, like every other item from any mod ever pleassssse

**Comment by Tfarcenim** [comment]
Fixed, but not worth pushing a release for 1 letter.

**Comment by StygianEmperor** [comment]
> the quiver item needs to be capitalized, like every other item from any mod ever pleassssse

[Quiver Redux Capitalized.zip](https://github.com/Tfarcenim/Quiver/files/5825574/Quiver.Redux.Capitalized.zip)
Here, it bothered me too. Unzip this folder and put "Quiver Redux Capitalized" into `.minecraft\resourcepacks` and activate it as you would any other resource pack; should fix it.

**Edit:** Actually, I'm pretty sure you don't even need to unzip it.
