### ISSUE TITLE
Quiver does not respect the shooting item's ammo predicate

### ISSUE THREAD

**Issue by Lykrast** [Tfarcenim/Quiver#3]
`ShootableItem` have a `getInventoryAmmoPredicate` that is used in the `findAmmo` call to get valid ammos, and the current mixin seems to completely ignore it and just uses the Quiver's own predicate. This causes a few compatibility issues when weapons can shoot ammo they weren't supposed to (like through adding more valid "arrows" with a datapack, or Guns Without Roses that uses it to find bullets).

I can't make a proper PR for it right now, but those predicates have an `and` function so you should be able to just combine the Quiver's and the shooting item's predicates when you do the call in the mixin.

*Note: yes the crash with tipped arrows in quiver that some guy on curseforge comment reported was on my side and I'm fixing it, but tipped arrows don't pass the guns' ammo predicate.*

*Note note: also I'm gonna translate your mod to french.*

**Comment by Tfarcenim** [comment]
fixed
