### ISSUE TITLE
Inventory profiles and Quiver w/ arrows causes items to disappear when picked up

### ISSUE THREAD

**Issue by Skuldafn0** [Tfarcenim/Quiver#5]
I play with the Inventory Profiles mod and recently discovered that when paired with the quiver mod, if the quiver has arrows in it, any item picked up will be deleted. It may also have the same effect with curios or item physics because I tested it with both and the items are deleted while arrows are in the quiver. If you need any more info I can try and test it some more.

**Comment by Tfarcenim** [comment]
should no longer be an issue, if it still occurs with 2.2 let me know
